---

- name: install necessary packages
  apt:
    name={{ item }}
    state=present
  with_items:
    - corosync
    - pacemaker

- name: generate corosync authkey
  command: /usr/sbin/corosync-keygen
  args:
    creates: /etc/corosync/authkey
  run_once: true

- name: copy corosync authkey to localhost
  fetch:
    src=/etc/corosync/authkey
    dest=files/{{ host_group }}/corosync/authkey
    flat=yes

- name: copy corosync authkey to all hosts
  copy:
    src=files/{{ host_group }}/corosync/authkey
    dest=/etc/corosync/authkey
    mode=0600
    owner=root
    group=root

- name: copy corosync configuration file
  template:
    src=corosync.conf.j2
    dest=/etc/corosync/corosync.conf
    owner=root
    group=root
    mode=0644

- name: copy pacemaker service file
  copy:
    src=pcmk
    dest=/etc/corosync/service.d/pcmk
    owner=root
    group=root
    mode=0644

- name: enable corosync startup
  lineinfile:
    dest=/etc/default/corosync
    line="START=yes"
    regexp="^START="

- name: start and enable corosync service
  service:
    name=corosync
    enabled=yes
    state=running

- name: start and enable pacemaker service
  service:
    name=pacemaker
    enabled=yes
    state=running

- name: copy crm default config file
  copy:
    src=crm_config_defaults.xml
    dest=/tmp/crm_config_defaults.xml

- name: import default crm configuration for two-node cluster
  shell: cibadmin --replace --xml-file /tmp/crm_config_defaults.xml && touch /var/lib/heartbeat/.crm_config_defaults_imported
  args:
    creates: /var/lib/heartbeat/.crm_config_defaults_imported
  run_once: true


