---

- name: ensure repostory packges are installed
  apt:
    pkg={{ item }}
    state=installed
  with_items:
    - python-apt
    - python-pycurl
  tags:
    - percona-tools


- name: install percona repostiry
  apt_key:
    url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1C4CBDCDCD2EFD2A
    id=CD2EFD2A
    state=present
  tags:
    - percona-tools

- name: set percona repostory deb
  apt_repository:
    repo='deb http://repo.percona.com/apt {{ ansible_lsb.codename }} main'
    state=present
  tags:
    - percona-tools

- name: set percona repostory deb-src
  apt_repository:
    repo='deb-src http://repo.percona.com/apt {{ ansible_lsb.codename }} main'
    state=present
  tags:
    - percona-tools

- name: install xtrabackup
  apt:
    pkg=xtrabackup
    state=installed
  tags:
    - percona-tools
