#######
# Install PGPool from Postgres PPA
#######

# Make sure the postgres apt-repository is present
- name: Add postgresql repository apt-key
  apt_key:
    id=ACCC4CF8
    url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state=present
  tags:
    - pgpool

- name: Add postgresql repository
  apt_repository:
    repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
    state=present
  tags:
    - pgpool

- name: Installing PGPool
  apt:
    name=pgpool2
    state=present
  tags:
    - pgpool

- name: Installing psycopg2
  apt:
    name=python-psycopg2
    state=present
  tags:
    - pgpool

#######
# Configure PGPool
#######

- name: Configuring PGPool
  template: src={{ item }}.j2 dest=/etc/pgpool2/{{ item }} mode=0644 owner=postgres group=postgres
  with_items:
   - pcp.conf
   - pgpool.conf
   - pool_hba.conf
  tags:
    - pgpool
  notify: restart pgpool

- name: Set proper ownership of files
  file:
    path=/etc/pgpool2
    recurse=yes
    owner=postgres
    group=postgres
  tags:
    - pgpool
  notify: restart pgpool

#######
# Start PGPool
#######

- name: Ensure PGPool is running
  service:
    name: pgpool2
    state: started
    enabled: yes

#######
# Generate PGPool users
#######

- name: Add users to pgpool password file
  shell: pg_md5 -u {{item.username}} -m {{item.password}}
  sudo: yes
  sudo_user: postgres
  with_items: db_users
  tags:
    - pgpool

#######
# Install shared SSH key for authless commands
#######

- name: Ensure postgres .ssh directory exists
  file:
    path: ~postgres/.ssh/
    state: directory
    group: postgres
    owner: postgres
  tags: postgresql

- name: Postgres user ssh key for file transfer
  copy:
    src="{{target_environment}}/files/sqlserver/ssh/{{item}}"
    dest=~postgres/.ssh/{{item}}
    group=postgres
    owner=postgres
    mode=0600
  with_items:
    - id_rsa
    - id_rsa.pub
    - authorized_keys
    - config
  tags:
    - pgpool

#######
# Install failover script
#######

- name: Copy failover script for pgpool
  copy:
    src='pgpool-do-failover'
    dest='/usr/local/bin/pgpool-do-failover'
    group=postgres
    owner=postgres
    mode=0700
  with_items:
    - id_rsa
    - id_rsa.pub
    - authorized_keys
  tags:
    - pgpool
