---

- name: install php
  apt:
    pkg={{ item }}
    state=installed
    install_recommends=no
    update_cache=yes
  with_items:
    - php5
    - php5-common
    - php5-cli
  when: php_version is not defined
  tags:
    - php

- name: check if apache is installed
  shell: "/usr/bin/dpkg-query -W -f='${Status}' apache2"
  register: apache_status
  changed_when: False
  when: apache_mod_php is defined
  tags:
    - php

- name: install php apache2 module
  apt:
    pkg=libapache2-mod-php5
    state=installed
    update_cache=yes
  when: apache_status.stdout == 'install ok installed' and apache_mod_php is defined
  notify:
   - restart apache
  tags:
    - php

- name: push external php ini configuration template
  template:
    src={{ php_ini_external_template }}
    dest=/etc/php5/{{ item }}/php.ini
    mode=0644
    owner=root
    group=root
    backup=yes
  with_items:
    - cli
    - apache2
  notify:
    - reload apache2
  when: php_ini_external_template is defined and apache_mod_php is defined
  tags:
    - php

- name: push custom php ini file
  copy:
    src={{ custom_php_ini_file }}
    dest=/etc/php5/{{ item }}/conf.d/30-custom-php.ini
    mode=0644
    owner=root
    group=root
    backup=yes
  with_items:
    - cli
    - apache2
  notify:
    - reload apache
  when: custom_php_ini_file is defined and apache_mod_php is defined
  tags:
    - php
