---

#- include: debian.yml
#  when: ansible_os_family == 'Debian'
#
#- include: redhat.yml
#  when: ansible_os_family == 'RedHat'

- include: {{ ansible_os_family }}.yml

- name: Munin server
  debug: msg="Your Munin server is reachable at http://{{ munin.server_ip }}/munin"
  when: munin_server is defined
