---

- name: install munin-server and dependencies
  yum:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - munin
    - httpd
    - mod_fcgid
  when: munin_server is defined
  tags:
    - munin
    - munin-server

- name: install munin-node
  yum:
    name=munin-node
    state=present
  tags:
    - munin
    - munin-node

- name: find the current apache version
  shell: "/usr/sbin/apachectl -v | awk '/Server version/ {print $3}' | cut -f2 -d/ | cut -f1-2 -d."
  register: apache_version
  when: munin_server is defined
  tags:
    - munin
    - munin-server

- name: copy template for munin server if applicable
  template:
    src=munin.conf.j2
    dest=/etc/munin/munin.conf
  when: munin_server is defined
  tags:
    - munin
    - munin-server

- name: copy template for munin-node
  template:
    src=munin-node.conf.j2
    dest=/etc/munin/munin-node.conf
  notify:
    - restart munin-node
  tags:
    - munin
    - munin-node

- name: enable all suggested plugins
  shell: /usr/sbin/munin-node-configure --shell 2>/dev/null | sh && touch /etc/munin/.suggests
  args: 
    creates: /etc/munin/.suggests
  notify:
    - restart munin-node
  tags:
    - munin
    - munin-node

- name: ensure munin-node is running and enabled
  service:
    name=munin-node
    state=running
    enabled=yes
  tags:
    - munin
    - munin-node

- name: ensure apache is running and enabled on munin server
  service:
    name=httpd
    state=running
    enabled=yes
  when: munin_server is defined
  tags:
    - munin
    - munin-server

- name: create munin www dir if applicable
  file:
    path=/var/www/munin
    state=directory
    owner=munin
    group=munin
    mode=0755
  when: munin_server is defined
  tags:
    - munin
    - munin-server

- name: create apache config for munin according to external template
  template:
    src={{ munin_apache_external_template }}
    dest=/etc/httpd/conf.d/munin.conf
  when: 
    - munin_server is defined
    - munin_apache_external_template is defined
  notify:
    - reload httpd
  tags:
    - munin
    - munin-server

- name: create apache config for munin if applicable
  template:
    src=apache.conf.j2
    dest=/etc/httpd/conf.d/munin.conf
  when: 
    - munin_server is defined
    - munin_apache_external_template is undefined
  notify:
    - reload httpd
  tags:
    - munin
    - munin-server

