---

- name: restart munin-node
  service:
    name=munin-node
    state=restarted

- name: restart apache
  service:
    name=apache2
    state=restarted

- name: restart httpd
  service:
    name=httpd
    state=restarted

- name: reload apache
  service:
    name=apache2
    state=reloaded

- name: reload httpd
  service:
    name=httpd
    state=reloaded

