#! /bin/sh
# Online recovery 2nd stage script
#
DATADIR=$1       # master dabatase cluster
DEST=$2          # hostname of the DB node to be recovered
DESTDIR=$3       # database cluster of the DB node to be recovered
PORT=5432        # PostgreSQL port number
archdir=/var/lib/postgresql/9.3/main/pg_archive/    # archive log directory

# Force to flush current value of sequences to xlog
psql -p $PORT -t -c 'SELECT datname FROM pg_database WHERE NOT datistemplate AND datallowconn' template1|
while read i
do
  if [ "$i" != "" ];then
    psql -p $PORT -c "SELECT setval(oid, nextval(oid)) FROM pg_class WHERE relkind = 'S'" $i
  fi
done

# Force an xlog switch (write archive so the to-be-recovered node can catch up on changes that came after disk dump)
psql -p $PORT -c "SELECT pgpool_switch_xlog('$archdir')" template1